import {
  Hospital,
  EmergencyCase,
  AuditLog,
  PatientProfile,
  LocationPreset,
  RouteOption,
} from '../src/types.js';

export const LOCATION_PRESETS: LocationPreset[] = [
  {
    country: 'India',
    stateRegion: 'Gujarat',
    city: 'Anand',
    area: 'Gamdi Vad / Station Road',
    lat: 22.5645,
    lng: 72.9289,
    label: 'Anand, Gujarat, India (Demo Default)',
  },
  {
    country: 'India',
    stateRegion: 'Gujarat',
    city: 'Ahmedabad',
    area: 'SG Highway / Bodakdev',
    lat: 23.0225,
    lng: 72.5714,
    label: 'Ahmedabad, Gujarat, India',
  },
  {
    country: 'USA',
    stateRegion: 'New York',
    city: 'New York',
    area: 'Manhattan',
    lat: 40.7128,
    lng: -74.0060,
    label: 'New York, NY, USA',
  },
  {
    country: 'UK',
    stateRegion: 'England',
    city: 'London',
    area: 'Westminster',
    lat: 51.5074,
    lng: -0.1278,
    label: 'London, England, UK',
  },
];

// Helper to get time strings
const now = new Date();
const minutesAgo = (min: number) => new Date(Date.now() - min * 60 * 1000).toISOString();
const hoursAgo = (hr: number) => new Date(Date.now() - hr * 60 * 60 * 1000).toISOString();
const inMinutes = (min: number) => new Date(Date.now() + min * 60 * 1000).toISOString();

export const INITIAL_HOSPITALS: Hospital[] = [
  // --- ANAND, GUJARAT, INDIA ---
  {
    id: 'HOSP-ANAND-02',
    name: 'Hospital B (Zydus Super-Speciality & Trauma Centre)',
    country: 'India',
    stateRegion: 'Gujarat',
    city: 'Anand',
    area: 'Lambhvel Road, Anand',
    address: 'Plot 14, Lambhvel Bypass Road, Anand, Gujarat 388001',
    lat: 22.5830,
    lng: 72.9520,
    contactNumber: '+91 2692 245000',
    emergencyContact: '+91 2692 245911',
    officialEmail: 'emergency@zydusanand.health',
    is24x7: true,
    verificationStatus: 'VERIFIED',
    registrationNumber: 'GJ-AND-MED-2021-9844',
    licenseNumber: 'LIC-EXP-2028-119',
    licenseIssueDate: '2022-01-15',
    licenseExpiryDate: '2028-01-14',
    accreditation: 'NABH Level 3 & NABL Accredited',
    authorizedPerson: {
      name: 'Dr. Ramesh Patel, MS (Trauma)',
      designation: 'Chief Medical Superintendent',
      contact: '+91 98250 11223',
      email: 'rpatel@zydusanand.health',
    },
    resources: {
      totalBeds: 180,
      availableBeds: 42,
      occupiedBeds: 138,
      emergencyBeds: 14,
      totalICU: 30,
      availableICU: 12,
      occupiedICU: 18,
      ventilatorsAvailable: 9,
      oxygenStatus: 'OPTIMAL',
      oxygenUnits: 94,
      cardiacCareAvailable: true,
      traumaCareAvailable: true,
      operationTheatreReady: true,
      ambulancesAvailable: 4,
      emergencyDoctorsOnDuty: 6,
      specialistsAvailable: [
        'Interventional Cardiologist',
        'Critical Care Intensivist',
        'Trauma Surgeon',
        'Senior Anesthetist'
      ],
    },
    medicines: [
      { id: 'm1', name: 'Aspirin 325mg (Chewable)', category: 'Cardiac', quantity: 450, unit: 'tabs', minimumThreshold: 100, expiryDate: '2027-09-01', status: 'AVAILABLE', lastUpdated: minutesAgo(12) },
      { id: 'm2', name: 'Atorvastatin 80mg', category: 'Cardiac', quantity: 280, unit: 'tabs', minimumThreshold: 80, expiryDate: '2027-11-15', status: 'AVAILABLE', lastUpdated: minutesAgo(12) },
      { id: 'm3', name: 'Heparin 25,000 IU/5ml', category: 'Anticoagulant', quantity: 64, unit: 'vials', minimumThreshold: 20, expiryDate: '2027-06-30', status: 'AVAILABLE', lastUpdated: minutesAgo(12) },
      { id: 'm4', name: 'Epinephrine 1mg/ml', category: 'Emergency Resuscitation', quantity: 120, unit: 'amps', minimumThreshold: 30, expiryDate: '2028-01-01', status: 'AVAILABLE', lastUpdated: minutesAgo(12) },
      { id: 'm5', name: 'Norepinephrine 4mg/4ml', category: 'Vasopressor', quantity: 38, unit: 'amps', minimumThreshold: 15, expiryDate: '2027-12-10', status: 'AVAILABLE', lastUpdated: minutesAgo(12) },
    ],
    bloodStock: [
      { group: 'O+', unitsAvailable: 18, status: 'AVAILABLE' },
      { group: 'O-', unitsAvailable: 6, status: 'AVAILABLE' },
      { group: 'A+', unitsAvailable: 12, status: 'AVAILABLE' },
      { group: 'B+', unitsAvailable: 15, status: 'AVAILABLE' },
    ],
    lastResourceUpdate: minutesAgo(15),
    nextUpdateDue: inMinutes(45),
    dataConfidence: 'HIGH',
  },
  {
    id: 'HOSP-ANAND-01',
    name: 'Hospital A (City Emergency Medical Centre)',
    country: 'India',
    stateRegion: 'Gujarat',
    city: 'Anand',
    area: 'Station Road, Anand',
    address: 'Near Old Bus Station, Anand, Gujarat 388001',
    lat: 22.5600,
    lng: 72.9350,
    contactNumber: '+91 2692 222111',
    emergencyContact: '+91 2692 222911',
    officialEmail: 'info@cityemergencyanand.org',
    is24x7: true,
    verificationStatus: 'VERIFIED',
    registrationNumber: 'GJ-AND-MED-2019-3321',
    licenseNumber: 'LIC-EXP-2027-402',
    licenseIssueDate: '2019-04-10',
    licenseExpiryDate: '2027-04-09',
    accreditation: 'State Healthcare Certified',
    authorizedPerson: {
      name: 'Dr. Hiren Joshi',
      designation: 'Medical Officer',
      contact: '+91 94260 88771',
      email: 'hjoshi@cityemergencyanand.org',
    },
    resources: {
      totalBeds: 60,
      availableBeds: 5,
      occupiedBeds: 55,
      emergencyBeds: 2,
      totalICU: 10,
      availableICU: 0, // FULL! No ICU available
      occupiedICU: 10,
      ventilatorsAvailable: 0,
      oxygenStatus: 'MODERATE',
      oxygenUnits: 22,
      cardiacCareAvailable: false, // NO CARDIAC CAPABILITY
      traumaCareAvailable: true,
      operationTheatreReady: false,
      ambulancesAvailable: 1,
      emergencyDoctorsOnDuty: 2,
      specialistsAvailable: ['General Surgeon', 'Emergency Physician'],
    },
    medicines: [
      { id: 'm6', name: 'Aspirin 325mg', category: 'Cardiac', quantity: 25, unit: 'tabs', minimumThreshold: 50, expiryDate: '2027-03-01', status: 'LOW', lastUpdated: minutesAgo(30) },
      { id: 'm7', name: 'Paracetamol IV 100ml', category: 'Analgesic', quantity: 80, unit: 'bottles', minimumThreshold: 20, expiryDate: '2028-02-15', status: 'AVAILABLE', lastUpdated: minutesAgo(30) },
    ],
    bloodStock: [
      { group: 'O+', unitsAvailable: 2, status: 'LOW' },
      { group: 'B+', unitsAvailable: 3, status: 'LOW' },
    ],
    lastResourceUpdate: minutesAgo(30),
    nextUpdateDue: inMinutes(30),
    dataConfidence: 'HIGH',
  },
  {
    id: 'HOSP-ANAND-03',
    name: 'Hospital C (Shree Krishna Cardiac Clinic)',
    country: 'India',
    stateRegion: 'Gujarat',
    city: 'Anand',
    area: 'Karamsad / GIDC Area',
    address: 'Medical Enclave, Karamsad-Anand Road, 388325',
    lat: 22.5520,
    lng: 72.9150,
    contactNumber: '+91 2692 228411',
    emergencyContact: '+91 2692 228999',
    officialEmail: 'emergency@skcardiac.org',
    is24x7: true,
    verificationStatus: 'VERIFIED',
    registrationNumber: 'GJ-AND-MED-2020-5512',
    licenseNumber: 'LIC-EXP-2027-889',
    licenseIssueDate: '2020-08-01',
    licenseExpiryDate: '2027-07-31',
    accreditation: 'NABH Accredited',
    authorizedPerson: {
      name: 'Dr. Ananya Shah',
      designation: 'Director of Emergency Services',
      contact: '+91 98980 44321',
      email: 'ashah@skcardiac.org',
    },
    resources: {
      totalBeds: 90,
      availableBeds: 8,
      occupiedBeds: 82,
      emergencyBeds: 3,
      totalICU: 15,
      availableICU: 0, // ALL 15 OCCUPIED
      occupiedICU: 15,
      ventilatorsAvailable: 1,
      oxygenStatus: 'OPTIMAL',
      oxygenUnits: 45,
      cardiacCareAvailable: true,
      traumaCareAvailable: true,
      operationTheatreReady: true,
      ambulancesAvailable: 2,
      emergencyDoctorsOnDuty: 4,
      specialistsAvailable: ['Cardiologist', 'Cath Lab Team'],
    },
    medicines: [
      { id: 'm8', name: 'Aspirin 325mg', category: 'Cardiac', quantity: 180, unit: 'tabs', minimumThreshold: 50, expiryDate: '2027-05-10', status: 'AVAILABLE', lastUpdated: minutesAgo(20) },
    ],
    bloodStock: [
      { group: 'O+', unitsAvailable: 5, status: 'AVAILABLE' },
    ],
    lastResourceUpdate: minutesAgo(20),
    nextUpdateDue: inMinutes(40),
    dataConfidence: 'HIGH',
  },
  {
    id: 'HOSP-ANAND-04',
    name: 'Anand Metro General Hospital (Stale Data Demo)',
    country: 'India',
    stateRegion: 'Gujarat',
    city: 'Anand',
    area: 'Amul Dairy Road, Anand',
    address: 'Near Amul Circle, Anand, Gujarat 388001',
    lat: 22.5690,
    lng: 72.9420,
    contactNumber: '+91 2692 260100',
    emergencyContact: '+91 2692 260108',
    officialEmail: 'admin@metroanand.org',
    is24x7: true,
    verificationStatus: 'VERIFIED',
    registrationNumber: 'GJ-AND-MED-2018-1249',
    licenseNumber: 'LIC-EXP-2026-903',
    licenseIssueDate: '2018-02-12',
    licenseExpiryDate: '2026-12-31',
    accreditation: 'State Health Board',
    authorizedPerson: {
      name: 'Dr. V. K. Desai',
      designation: 'Superintendent',
      contact: '+91 98240 77112',
      email: 'vkdesai@metroanand.org',
    },
    resources: {
      totalBeds: 120,
      availableBeds: 25,
      occupiedBeds: 95,
      emergencyBeds: 6,
      totalICU: 18,
      availableICU: 5,
      occupiedICU: 13,
      ventilatorsAvailable: 3,
      oxygenStatus: 'MODERATE',
      oxygenUnits: 30,
      cardiacCareAvailable: true,
      traumaCareAvailable: true,
      operationTheatreReady: true,
      ambulancesAvailable: 2,
      emergencyDoctorsOnDuty: 3,
      specialistsAvailable: ['General Physician'],
    },
    medicines: [],
    bloodStock: [],
    lastResourceUpdate: hoursAgo(5), // 5 HOURS STALE!
    nextUpdateDue: hoursAgo(4), // OVERDUE!
    dataConfidence: 'LOW', // Reduced confidence due to stale data
  },
  {
    id: 'HOSP-ANAND-05',
    name: 'Apex Medicare Center (Suspended Demo)',
    country: 'India',
    stateRegion: 'Gujarat',
    city: 'Anand',
    area: 'Vidyanagar Road, Anand',
    address: '102 Complex, Vidyanagar Road, Anand 388120',
    lat: 22.5480,
    lng: 72.9230,
    contactNumber: '+91 2692 238000',
    emergencyContact: '+91 2692 238911',
    officialEmail: 'contact@apexmedicare.com',
    is24x7: false,
    verificationStatus: 'SUSPENDED', // SUSPENDED - NOT TO BE RECOMMENDED
    registrationNumber: 'GJ-AND-MED-2017-0092',
    licenseNumber: 'LIC-EXP-2024-110 (EXPIRED)',
    licenseIssueDate: '2017-03-01',
    licenseExpiryDate: '2024-03-01',
    accreditation: 'Suspended pending investigation',
    authorizedPerson: {
      name: 'P. Dave',
      designation: 'Administrator',
      contact: '+91 98790 33445',
      email: 'pdave@apexmedicare.com',
    },
    resources: {
      totalBeds: 40,
      availableBeds: 15,
      occupiedBeds: 25,
      emergencyBeds: 2,
      totalICU: 4,
      availableICU: 2,
      occupiedICU: 2,
      ventilatorsAvailable: 1,
      oxygenStatus: 'LOW',
      oxygenUnits: 8,
      cardiacCareAvailable: false,
      traumaCareAvailable: false,
      operationTheatreReady: false,
      ambulancesAvailable: 0,
      emergencyDoctorsOnDuty: 1,
      specialistsAvailable: [],
    },
    medicines: [],
    bloodStock: [],
    lastResourceUpdate: hoursAgo(48),
    nextUpdateDue: hoursAgo(47),
    dataConfidence: 'LOW',
  },

  // --- AHMEDABAD, GUJARAT, INDIA ---
  {
    id: 'HOSP-AHM-01',
    name: 'Apollo Hospitals International Limited',
    country: 'India',
    stateRegion: 'Gujarat',
    city: 'Ahmedabad',
    area: 'Gandhinagar - Ahmedabad Link Road',
    address: 'Plot 1A, GIDC Estate, Bhat, Ahmedabad 382428',
    lat: 23.0975,
    lng: 72.6105,
    contactNumber: '+91 79 6670 1800',
    emergencyContact: '+91 79 6670 1066',
    officialEmail: 'emergency_ahmedabad@apollohospitals.com',
    is24x7: true,
    verificationStatus: 'VERIFIED',
    registrationNumber: 'GJ-AHM-MED-2015-8821',
    licenseNumber: 'LIC-EXP-2028-401',
    licenseIssueDate: '2015-05-12',
    licenseExpiryDate: '2028-05-11',
    accreditation: 'JCI & NABH Accredited',
    authorizedPerson: {
      name: 'Dr. Neha Shah, MD',
      designation: 'Emergency Director',
      contact: '+91 99090 12345',
      email: 'nshah@apollohospitals.com',
    },
    resources: {
      totalBeds: 280,
      availableBeds: 68,
      occupiedBeds: 212,
      emergencyBeds: 25,
      totalICU: 50,
      availableICU: 18,
      occupiedICU: 32,
      ventilatorsAvailable: 14,
      oxygenStatus: 'OPTIMAL',
      oxygenUnits: 150,
      cardiacCareAvailable: true,
      traumaCareAvailable: true,
      operationTheatreReady: true,
      ambulancesAvailable: 8,
      emergencyDoctorsOnDuty: 10,
      specialistsAvailable: ['Cardiac Electrophysiologist', 'Trauma Intensivist', 'Neurosurgeon'],
    },
    medicines: [
      { id: 'm9', name: 'Aspirin 325mg', category: 'Cardiac', quantity: 600, unit: 'tabs', minimumThreshold: 100, expiryDate: '2027-10-01', status: 'AVAILABLE', lastUpdated: minutesAgo(10) },
    ],
    bloodStock: [
      { group: 'O+', unitsAvailable: 30, status: 'AVAILABLE' },
      { group: 'O-', unitsAvailable: 10, status: 'AVAILABLE' },
    ],
    lastResourceUpdate: minutesAgo(10),
    nextUpdateDue: inMinutes(50),
    dataConfidence: 'HIGH',
  },

  // --- NEW YORK, USA ---
  {
    id: 'HOSP-NYC-01',
    name: 'NewYork-Presbyterian Hospital / Weill Cornell',
    country: 'USA',
    stateRegion: 'New York',
    city: 'New York',
    area: 'Upper East Side, Manhattan',
    address: '525 E 68th St, New York, NY 10065',
    lat: 40.7651,
    lng: -73.9542,
    contactNumber: '+1 212-746-5454',
    emergencyContact: '+1 212-746-5000',
    officialEmail: 'emergency@nyp.org',
    is24x7: true,
    verificationStatus: 'VERIFIED',
    registrationNumber: 'US-NY-DOH-88231',
    licenseNumber: 'HOSP-NY-2029-771',
    licenseIssueDate: '2020-01-01',
    licenseExpiryDate: '2029-01-01',
    accreditation: 'The Joint Commission Certified Level 1 Trauma',
    authorizedPerson: {
      name: 'Dr. Marcus Vance, MD, FACEP',
      designation: 'Chair of Emergency Medicine',
      contact: '+1 212-555-0199',
      email: 'mvance@nyp.org',
    },
    resources: {
      totalBeds: 450,
      availableBeds: 92,
      occupiedBeds: 358,
      emergencyBeds: 35,
      totalICU: 65,
      availableICU: 24,
      occupiedICU: 41,
      ventilatorsAvailable: 20,
      oxygenStatus: 'OPTIMAL',
      oxygenUnits: 200,
      cardiacCareAvailable: true,
      traumaCareAvailable: true,
      operationTheatreReady: true,
      ambulancesAvailable: 12,
      emergencyDoctorsOnDuty: 14,
      specialistsAvailable: ['Interventional Cardiologist', 'Cardiothoracic Surgeon', 'Trauma Director'],
    },
    medicines: [],
    bloodStock: [
      { group: 'O-', unitsAvailable: 24, status: 'AVAILABLE' },
    ],
    lastResourceUpdate: minutesAgo(22),
    nextUpdateDue: inMinutes(38),
    dataConfidence: 'HIGH',
  },

  // --- LONDON, UK ---
  {
    id: 'HOSP-LDN-01',
    name: "St Thomas' Hospital Emergency Department",
    country: 'UK',
    stateRegion: 'England',
    city: 'London',
    area: 'Lambeth, London',
    address: 'Westminster Bridge Rd, London SE1 7EH',
    lat: 51.4988,
    lng: -0.1186,
    contactNumber: '+44 20 7188 7188',
    emergencyContact: '+44 20 7188 8888',
    officialEmail: 'emergency@gstt.nhs.uk',
    is24x7: true,
    verificationStatus: 'VERIFIED',
    registrationNumber: 'NHS-TRUST-LON-0041',
    licenseNumber: 'CQC-OUTSTANDING-2028',
    licenseIssueDate: '2021-03-10',
    licenseExpiryDate: '2028-03-09',
    accreditation: 'CQC Outstanding & Major Trauma Centre',
    authorizedPerson: {
      name: 'Dr. Charlotte Sterling, FRCP',
      designation: 'Clinical Lead Emergency Medicine',
      contact: '+44 7700 900123',
      email: 'csterling@gstt.nhs.uk',
    },
    resources: {
      totalBeds: 380,
      availableBeds: 74,
      occupiedBeds: 306,
      emergencyBeds: 30,
      totalICU: 48,
      availableICU: 16,
      occupiedICU: 32,
      ventilatorsAvailable: 15,
      oxygenStatus: 'OPTIMAL',
      oxygenUnits: 180,
      cardiacCareAvailable: true,
      traumaCareAvailable: true,
      operationTheatreReady: true,
      ambulancesAvailable: 10,
      emergencyDoctorsOnDuty: 11,
      specialistsAvailable: ['Consultant Cardiologist', 'Trauma Lead'],
    },
    medicines: [],
    bloodStock: [],
    lastResourceUpdate: minutesAgo(18),
    nextUpdateDue: inMinutes(42),
    dataConfidence: 'HIGH',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'AUD-001',
    actorId: 'ADM-PRAANJEEV-1',
    actorName: 'System Verification Bot & Auditor',
    actorRole: 'SYSTEM_ADMIN',
    action: 'HOSPITAL_VERIFIED',
    entityType: 'HOSPITAL',
    entityId: 'HOSP-ANAND-02',
    newValue: 'VERIFIED (NABH Level 3 Inspection Completed)',
    reason: 'Multi-level legal document & infrastructure verification approved',
    timestamp: hoursAgo(24),
  },
  {
    id: 'AUD-002',
    actorId: 'STF-PATEL-6',
    actorName: 'Dr. Ramesh Patel',
    actorRole: 'HOSPITAL_STAFF',
    action: 'RESOURCE_UPDATE',
    entityType: 'RESOURCE',
    entityId: 'HOSP-ANAND-02',
    oldValue: 'Available ICU: 10, Available Beds: 40',
    newValue: 'Available ICU: 12, Available Beds: 42',
    reason: 'Routine hourly bed sync after discharge',
    timestamp: minutesAgo(15),
  },
  {
    id: 'AUD-003',
    actorId: 'ADM-SYS-04',
    actorName: 'System Anomaly Detector',
    actorRole: 'SYSTEM_ADMIN',
    action: 'DATA_ANOMALY_BLOCKED',
    entityType: 'RESOURCE',
    entityId: 'HOSP-ANAND-01',
    oldValue: 'Total ICU: 10, Available ICU: 0',
    newValue: 'Blocked Input: Available ICU: 25',
    reason: 'Rejected: Available ICU (25) exceeded Total ICU capacity (10)',
    timestamp: hoursAgo(2),
    anomalyDetected: true,
  },
  {
    id: 'AUD-004',
    actorId: 'ADM-PRAANJEEV-1',
    actorName: 'Chief Inspector Admin',
    actorRole: 'SYSTEM_ADMIN',
    action: 'HOSPITAL_SUSPENDED',
    entityType: 'HOSPITAL',
    entityId: 'HOSP-ANAND-05',
    oldValue: 'VERIFIED',
    newValue: 'SUSPENDED',
    reason: 'Failure to renew medical license (Expired 2024-03-01) & zero on-duty cardiac staff',
    timestamp: hoursAgo(48),
  }
];

export const INITIAL_PATIENT: PatientProfile = {
  id: 'PAT-IND-2026-045',
  name: 'Rajeshbhai M. Patel',
  email: 'rajesh.patel.anand@example.com',
  phone: '+91 98251 44556',
  age: 45,
  gender: 'MALE',
  bloodGroup: 'B+',
  emergencyContact: {
    name: 'Hansaben Patel',
    phone: '+91 98251 44557',
    relation: 'Spouse',
  },
  isVerified: true,
  conditions: ['Mild Hypertension', 'Borderline Hyperlipidemia'],
  allergies: ['Penicillin', 'Sulfa Drugs'],
  medications: ['Telmisartan 40mg (OD)', 'Atorvastatin 10mg (HS)'],
  pastSurgeries: ['Appendectomy (2018)'],
};
